/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author DESKTOP-6A9B
 */
public class PasarelaDePago extends javax.swing.JDialog {

    VentanaPrincipal vMain = new VentanaPrincipal();

    public PasarelaDePago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jTextFieldNombreUsuario1 = new javax.swing.JTextField();
        jTextFieldNombreUsuario2 = new javax.swing.JTextField();
        jTextFieldNombreUsuario3 = new javax.swing.JTextField();
        jLabelButtonVolverAtrás = new javax.swing.JLabel();
        jLabelFondoDePagos = new javax.swing.JLabel();
        jButtonVolverAtrásButton = new javax.swing.JButton();
        jButtonPAGAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombreUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextFieldNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreUsuario.setToolTipText("");
        jTextFieldNombreUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextFieldNombreUsuario.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jTextFieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 310, 20));

        jTextFieldNombreUsuario1.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombreUsuario1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextFieldNombreUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreUsuario1.setToolTipText("");
        jTextFieldNombreUsuario1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextFieldNombreUsuario1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jTextFieldNombreUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 310, 20));

        jTextFieldNombreUsuario2.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombreUsuario2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextFieldNombreUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreUsuario2.setToolTipText("");
        jTextFieldNombreUsuario2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextFieldNombreUsuario2.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jTextFieldNombreUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 190, 20));

        jTextFieldNombreUsuario3.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombreUsuario3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextFieldNombreUsuario3.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreUsuario3.setToolTipText("");
        jTextFieldNombreUsuario3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextFieldNombreUsuario3.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jTextFieldNombreUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuario3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 50, 20));

        jLabelButtonVolverAtrás.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttonVolverAtras.png"))); // NOI18N
        getContentPane().add(jLabelButtonVolverAtrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelFondoDePagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPagos.png"))); // NOI18N
        getContentPane().add(jLabelFondoDePagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonVolverAtrásButton.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtrásButton.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtrásButton.setBorder(null);
        jButtonVolverAtrásButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrásButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtrásButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));

        jButtonPAGAR.setBackground(new java.awt.Color(200, 235, 241));
        jButtonPAGAR.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButtonPAGAR.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPAGAR.setBorder(null);
        jButtonPAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPAGARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPAGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 170, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUsuarioActionPerformed

    private void jTextFieldNombreUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUsuario1ActionPerformed

    private void jTextFieldNombreUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUsuario2ActionPerformed

    private void jTextFieldNombreUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUsuario3ActionPerformed

    private void jButtonPAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPAGARActionPerformed

        Timer timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

                VentanaExito vExito = new VentanaExito(vMain, true);
                vExito.setVisible(true);

                ((Timer) e.getSource()).stop();
            }
        });

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_jButtonPAGARActionPerformed

    private void jButtonVolverAtrásButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrásButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVolverAtrásButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasarelaDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasarelaDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasarelaDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasarelaDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasarelaDePago dialog = new PasarelaDePago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPAGAR;
    private javax.swing.JButton jButtonVolverAtrásButton;
    private javax.swing.JLabel jLabelButtonVolverAtrás;
    private javax.swing.JLabel jLabelFondoDePagos;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    private javax.swing.JTextField jTextFieldNombreUsuario1;
    private javax.swing.JTextField jTextFieldNombreUsuario2;
    private javax.swing.JTextField jTextFieldNombreUsuario3;
    // End of variables declaration//GEN-END:variables
}
