/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 *
 * @author DESKTOP-6A9B
 */
public class SeleccionarOpcionesHab extends javax.swing.JDialog {

    /**
     * Creates new form SeleccionarOpcionesHab
     */
    public SeleccionarOpcionesHab(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabelReservaDeHabit = new javax.swing.JLabel();
        jLabelOpcion1 = new javax.swing.JLabel();
        jLabelOpcion2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabelOpcion3 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabelOpcion4 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabelOpcion5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanelButtonBuscarDesti = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jButtonBuscarDestino = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 30, 30));

        jLabelReservaDeHabit.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabelReservaDeHabit.setText("OPCIONES DEL SERVICIO");
        getContentPane().add(jLabelReservaDeHabit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 410, -1));

        jLabelOpcion1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelOpcion1.setText("SPA y MASAJES");
        getContentPane().add(jLabelOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, -1));

        jLabelOpcion2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelOpcion2.setText("DESAYUNO");
        getContentPane().add(jLabelOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, -1));
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 30, 30));

        jLabelOpcion3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelOpcion3.setText("PARKING");
        getContentPane().add(jLabelOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 30, 30));

        jLabelOpcion4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelOpcion4.setText("PISTA DE PÁDEL");
        getContentPane().add(jLabelOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 30, 30));

        jLabelOpcion5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabelOpcion5.setText("ACT. PARA NIÑOS");
        getContentPane().add(jLabelOpcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 30, 30));

        jPanelButtonBuscarDesti.setBackground(new java.awt.Color(200, 235, 241));
        jPanelButtonBuscarDesti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("GUARDAR OPCIONES");

        javax.swing.GroupLayout jPanelButtonBuscarDestiLayout = new javax.swing.GroupLayout(jPanelButtonBuscarDesti);
        jPanelButtonBuscarDesti.setLayout(jPanelButtonBuscarDestiLayout);
        jPanelButtonBuscarDestiLayout.setHorizontalGroup(
            jPanelButtonBuscarDestiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonBuscarDestiLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(52, 52, 52))
        );
        jPanelButtonBuscarDestiLayout.setVerticalGroup(
            jPanelButtonBuscarDestiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonBuscarDestiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelButtonBuscarDesti, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoOpciones.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 490));

        jButtonBuscarDestino.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarDestino.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButtonBuscarDestino.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscarDestino.setBorder(null);
        jButtonBuscarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDestinoActionPerformed

    }//GEN-LAST:event_jButtonBuscarDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionesHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionesHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionesHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarOpcionesHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionarOpcionesHab dialog = new SeleccionarOpcionesHab(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarDestino;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelOpcion1;
    private javax.swing.JLabel jLabelOpcion2;
    private javax.swing.JLabel jLabelOpcion3;
    private javax.swing.JLabel jLabelOpcion4;
    private javax.swing.JLabel jLabelOpcion5;
    private javax.swing.JLabel jLabelReservaDeHabit;
    private javax.swing.JPanel jPanelButtonBuscarDesti;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
